---
deployment:
  tasks:
    # Terminal ciktiniza gore dogru klasor yolu:
    # /home/haslim/public_html/ofis.billurguleraslim.av.tr/
    - export DEPLOYPATH=/home/haslim/public_html/ofis.billurguleraslim.av.tr/
    
    # 1. Dist klasöründeki (Bilgisayarinizda Build edilmiş) dosyaları sunucuya kopyala
    # -R recursive (klasörlerle birlikte) kopyalar
    - /bin/cp -R dist/* $DEPLOYPATH
    
    # 2. .htaccess dosyasını kopyala (Sayfa yönlendirmeleri için şart)
    - /bin/cp .htaccess $DEPLOYPATH
